build-slurm:
  tags:
  - slurm
  script:
  - source $HOME/spack/share/spack/setup-env.sh
  - spack env activate x86-login
  - spack load reframe
  - reframe -c .build-tools/reframe/lpf_tests.py -C .build-tools/reframe/settings.py -r --stage=/storage/users/gitlab-runner/stage/ --keep-stage-files
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    when: always
    paths:
      - /storage/users/gitlab-runner/stage/BZ/arm-sequential/PrgEnv-default/LPFFuncTests/rfm_job*
      - /storage/users/gitlab-runner/lpf_repo/build/junit/